inno:
  build: .
  volumes:
    - ./:/scripts
  links:
    - xserver:xserver
  volumes_from:
    - xserver
  environment:
    - DISPLAY=xserver:0
xserver:
  image: suchja/x11server
  ports:
    - 5900:5900
  environment:
    VNC_PASSWORD: 1234